# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/agh/Desktop/projekt/project_pandemonium/project_pandemonium

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/agh/Desktop/projekt/project_pandemonium/project_pandemonium

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/agh/Desktop/projekt/project_pandemonium/project_pandemonium/CMakeFiles /home/agh/Desktop/projekt/project_pandemonium/project_pandemonium//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/agh/Desktop/projekt/project_pandemonium/project_pandemonium/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pandemonium

# Build rule for target.
pandemonium: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pandemonium
.PHONY : pandemonium

# fast build rule for target.
pandemonium/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/build
.PHONY : pandemonium/fast

src/CommandInterpreter.o: src/CommandInterpreter.cpp.o
.PHONY : src/CommandInterpreter.o

# target to build an object file
src/CommandInterpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/CommandInterpreter.cpp.o
.PHONY : src/CommandInterpreter.cpp.o

src/CommandInterpreter.i: src/CommandInterpreter.cpp.i
.PHONY : src/CommandInterpreter.i

# target to preprocess a source file
src/CommandInterpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/CommandInterpreter.cpp.i
.PHONY : src/CommandInterpreter.cpp.i

src/CommandInterpreter.s: src/CommandInterpreter.cpp.s
.PHONY : src/CommandInterpreter.s

# target to generate assembly for a file
src/CommandInterpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/CommandInterpreter.cpp.s
.PHONY : src/CommandInterpreter.cpp.s

src/MiniGameManager.o: src/MiniGameManager.cpp.o
.PHONY : src/MiniGameManager.o

# target to build an object file
src/MiniGameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/MiniGameManager.cpp.o
.PHONY : src/MiniGameManager.cpp.o

src/MiniGameManager.i: src/MiniGameManager.cpp.i
.PHONY : src/MiniGameManager.i

# target to preprocess a source file
src/MiniGameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/MiniGameManager.cpp.i
.PHONY : src/MiniGameManager.cpp.i

src/MiniGameManager.s: src/MiniGameManager.cpp.s
.PHONY : src/MiniGameManager.s

# target to generate assembly for a file
src/MiniGameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/MiniGameManager.cpp.s
.PHONY : src/MiniGameManager.cpp.s

src/gameplay_draw.o: src/gameplay_draw.cpp.o
.PHONY : src/gameplay_draw.o

# target to build an object file
src/gameplay_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/gameplay_draw.cpp.o
.PHONY : src/gameplay_draw.cpp.o

src/gameplay_draw.i: src/gameplay_draw.cpp.i
.PHONY : src/gameplay_draw.i

# target to preprocess a source file
src/gameplay_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/gameplay_draw.cpp.i
.PHONY : src/gameplay_draw.cpp.i

src/gameplay_draw.s: src/gameplay_draw.cpp.s
.PHONY : src/gameplay_draw.s

# target to generate assembly for a file
src/gameplay_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/gameplay_draw.cpp.s
.PHONY : src/gameplay_draw.cpp.s

src/gameplay_update.o: src/gameplay_update.cpp.o
.PHONY : src/gameplay_update.o

# target to build an object file
src/gameplay_update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/gameplay_update.cpp.o
.PHONY : src/gameplay_update.cpp.o

src/gameplay_update.i: src/gameplay_update.cpp.i
.PHONY : src/gameplay_update.i

# target to preprocess a source file
src/gameplay_update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/gameplay_update.cpp.i
.PHONY : src/gameplay_update.cpp.i

src/gameplay_update.s: src/gameplay_update.cpp.s
.PHONY : src/gameplay_update.s

# target to generate assembly for a file
src/gameplay_update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/gameplay_update.cpp.s
.PHONY : src/gameplay_update.cpp.s

src/globals.o: src/globals.cpp.o
.PHONY : src/globals.o

# target to build an object file
src/globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/globals.cpp.o
.PHONY : src/globals.cpp.o

src/globals.i: src/globals.cpp.i
.PHONY : src/globals.i

# target to preprocess a source file
src/globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/globals.cpp.i
.PHONY : src/globals.cpp.i

src/globals.s: src/globals.cpp.s
.PHONY : src/globals.s

# target to generate assembly for a file
src/globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/globals.cpp.s
.PHONY : src/globals.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/minigames/RotatingRectangleGame.o: src/minigames/RotatingRectangleGame.cpp.o
.PHONY : src/minigames/RotatingRectangleGame.o

# target to build an object file
src/minigames/RotatingRectangleGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/minigames/RotatingRectangleGame.cpp.o
.PHONY : src/minigames/RotatingRectangleGame.cpp.o

src/minigames/RotatingRectangleGame.i: src/minigames/RotatingRectangleGame.cpp.i
.PHONY : src/minigames/RotatingRectangleGame.i

# target to preprocess a source file
src/minigames/RotatingRectangleGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/minigames/RotatingRectangleGame.cpp.i
.PHONY : src/minigames/RotatingRectangleGame.cpp.i

src/minigames/RotatingRectangleGame.s: src/minigames/RotatingRectangleGame.cpp.s
.PHONY : src/minigames/RotatingRectangleGame.s

# target to generate assembly for a file
src/minigames/RotatingRectangleGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/minigames/RotatingRectangleGame.cpp.s
.PHONY : src/minigames/RotatingRectangleGame.cpp.s

src/settings_draw.o: src/settings_draw.cpp.o
.PHONY : src/settings_draw.o

# target to build an object file
src/settings_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/settings_draw.cpp.o
.PHONY : src/settings_draw.cpp.o

src/settings_draw.i: src/settings_draw.cpp.i
.PHONY : src/settings_draw.i

# target to preprocess a source file
src/settings_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/settings_draw.cpp.i
.PHONY : src/settings_draw.cpp.i

src/settings_draw.s: src/settings_draw.cpp.s
.PHONY : src/settings_draw.s

# target to generate assembly for a file
src/settings_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/settings_draw.cpp.s
.PHONY : src/settings_draw.cpp.s

src/settings_update.o: src/settings_update.cpp.o
.PHONY : src/settings_update.o

# target to build an object file
src/settings_update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/settings_update.cpp.o
.PHONY : src/settings_update.cpp.o

src/settings_update.i: src/settings_update.cpp.i
.PHONY : src/settings_update.i

# target to preprocess a source file
src/settings_update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/settings_update.cpp.i
.PHONY : src/settings_update.cpp.i

src/settings_update.s: src/settings_update.cpp.s
.PHONY : src/settings_update.s

# target to generate assembly for a file
src/settings_update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/settings_update.cpp.s
.PHONY : src/settings_update.cpp.s

src/title_draw.o: src/title_draw.cpp.o
.PHONY : src/title_draw.o

# target to build an object file
src/title_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/title_draw.cpp.o
.PHONY : src/title_draw.cpp.o

src/title_draw.i: src/title_draw.cpp.i
.PHONY : src/title_draw.i

# target to preprocess a source file
src/title_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/title_draw.cpp.i
.PHONY : src/title_draw.cpp.i

src/title_draw.s: src/title_draw.cpp.s
.PHONY : src/title_draw.s

# target to generate assembly for a file
src/title_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/title_draw.cpp.s
.PHONY : src/title_draw.cpp.s

src/title_update.o: src/title_update.cpp.o
.PHONY : src/title_update.o

# target to build an object file
src/title_update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/title_update.cpp.o
.PHONY : src/title_update.cpp.o

src/title_update.i: src/title_update.cpp.i
.PHONY : src/title_update.i

# target to preprocess a source file
src/title_update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/title_update.cpp.i
.PHONY : src/title_update.cpp.i

src/title_update.s: src/title_update.cpp.s
.PHONY : src/title_update.s

# target to generate assembly for a file
src/title_update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pandemonium.dir/build.make CMakeFiles/pandemonium.dir/src/title_update.cpp.s
.PHONY : src/title_update.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pandemonium"
	@echo "... src/CommandInterpreter.o"
	@echo "... src/CommandInterpreter.i"
	@echo "... src/CommandInterpreter.s"
	@echo "... src/MiniGameManager.o"
	@echo "... src/MiniGameManager.i"
	@echo "... src/MiniGameManager.s"
	@echo "... src/gameplay_draw.o"
	@echo "... src/gameplay_draw.i"
	@echo "... src/gameplay_draw.s"
	@echo "... src/gameplay_update.o"
	@echo "... src/gameplay_update.i"
	@echo "... src/gameplay_update.s"
	@echo "... src/globals.o"
	@echo "... src/globals.i"
	@echo "... src/globals.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/minigames/RotatingRectangleGame.o"
	@echo "... src/minigames/RotatingRectangleGame.i"
	@echo "... src/minigames/RotatingRectangleGame.s"
	@echo "... src/settings_draw.o"
	@echo "... src/settings_draw.i"
	@echo "... src/settings_draw.s"
	@echo "... src/settings_update.o"
	@echo "... src/settings_update.i"
	@echo "... src/settings_update.s"
	@echo "... src/title_draw.o"
	@echo "... src/title_draw.i"
	@echo "... src/title_draw.s"
	@echo "... src/title_update.o"
	@echo "... src/title_update.i"
	@echo "... src/title_update.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

